### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [cedx/akismet.js#8]
Hi @cedx  I am a logo designer.

I contribute to open source projects that do not have logo. I designed a logo for akismet.js. Please tell me what you think. I will wait for feedback. Best regards.

![AKİSMET](https://user-images.githubusercontent.com/36298335/56821195-5f7cc780-6856-11e9-9806-1b55cf046ced.jpg)

Readme view;

![akismett](https://user-images.githubusercontent.com/36298335/56821263-80451d00-6856-11e9-8469-2aca1b9b4329.png)

**Comment by cedx** [comment]
Thanks a lot for your contribution. I appreciate it, and it would be a pleasure to add this logo to the project. For this, I need a pull request (put the resources into the `doc/img` folder) in which you indicate how you would like to be credited (a link to your GitHub account, or a link to your website, your pseudonym or your real name, maybe your mail address, etc.).

Concerning the logo itself: I have several flavors of this project, a JS one of course, but also Dart and PHP ones. See: https://github.com/cedx?tab=repositories&q=akismet

It would be huge to have a variant of this logo for each project. To distinguish each of these projects, I use a color code: yellow for JS, blue for Dart, purple for PHP.
See: https://dev.belin.io/akismet.js, https://dev.belin.io/akismet.dart, https://dev.belin.io/akismet.php.

So I think it would be a bit better to find a way to highlight the letters `js` in the logo, preferably with a tone of yellow. It's up to you to see what makes the best: maybe yellow letters with a black outline?

**Comment by cedx** [comment]
@reallinfo I'm closing this issue. But if you want to contribute, don't hesitate to submit a pull request.
